### ISSUE TITLE
The readme should mention that band9comp needs to be inside the working directory

### ISSUE THREAD

**Issue by TLATER** [docmudkipz/makeanim#2]
Fairly obvious I think, it took me some 10 minutes of debugging to find that.

**Comment by docmudkipz** [comment]
I fail to see how this is an issue. If you couldn't figure this out within 5 minutes of the script tossing errors at you then you shouldn't be using Ban9Comp. Nor has Ban9Comp ever been recommended to be used by either Wolfvak or myself due to how BA9 currently works with the compressed files.

**Comment by TLATER** [comment]
I know this is closed, but the Readme should really then at least note that compression is only recommended if you know what you are doing.

Also, the script doesn't throw errors because those are cleared away by default. It's impossible to see what's going wrong without editing the script.

**Comment by docmudkipz** [comment]
The proper way to check for errors in a batch or any shell script is by running it from the CLI itself. It should never take more than it takes for the script to run to debug it. Running it from a normal CLI window prevents it from clearing itself.
https://gyazo.com/53991068a8e8a016a0a3928b795ba537

**Comment by TLATER** [comment]
I'm not sure what terminal you're using, but that's not the default behaviour:

https://linux.die.net/man/1/clear

At least screen, xterm, linux, rxvt, tmux and termite behave that way on this script on my bare-metal arch install, and I've never used a terminal in which that would not have happened... Except a misconfigured (no terminfo) docker one.

**Comment by docmudkipz** [comment]
In linux you could've run `sh -v makeanim.sh` and it accomplishes everything you wanted

**Comment by TLATER** [comment]
... That puts it in debug mode. bash's debug mode does not avoid executing the clear command.

**Comment by docmudkipz** [comment]
Then I dont see how it takes longer than 30s to comment all of the 5 clears in the script. It doesnt change the fact it shouldnt take longer than 2 minutes to figure out that something isnt in the work directory. It should've been the first thing you done after realizing compression isnt working nor does it take longer than 5 seconds to open the file and check the compression section of the script. Its as clean as I can make it and commented to boot.
