### ISSUE TITLE
Support CLI arguments on top of the readline interface

### ISSUE THREAD

**Issue by TLATER** [docmudkipz/makeanim#3]
While not particularly important for functionality, I believe using getopt-style CLI arguments and a usage string would provide a more standard UI for this script.

I'd be happy to provide a pull request for this.

**Comment by docmudkipz** [comment]
Feel free to do this on your own but it takes away from the fact that the script is meant to handhold the user by just being able to double click the thing and have it guide the user. The most I ask is that you don't publicly distribute your own edit if its still majority my own.
